{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bvar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BVAR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BVAR/BVAR_{{ version }}.tar.gz
  sha256: b43243dc2ab2d5e6ac3bf5d00c77c36416419d44f616acac837f1d272f3a6e15

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mvtnorm
  run:
    - r-base
    - r-mvtnorm

test:
  commands:
    - $R -e "library('BVAR')"           # [not win]
    - "\"%R%\" -e \"library('BVAR')\""  # [win]

about:
  home: https://github.com/nk027/bvar
  license: GPL-3.0-only
  summary: Estimation of hierarchical Bayesian vector autoregressive models following Kuschnig & Vashold (2021) <doi:10.18637/jss.v100.i14>. Implements hierarchical prior selection for conjugate priors in the fashion of Giannone, Lenza & Primiceri (2015) <doi:10.1162/REST_a_00483>. Functions to compute and identify impulse
    responses, calculate forecasts, forecast error variance decompositions and scenarios are available. Several methods to print, plot and summarise results facilitate analysis.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - SulphurFH

# Package: BVAR
# Type: Package
# Title: Hierarchical Bayesian Vector Autoregression
# Version: 1.0.4
# Date: 2023-03-08
# Authors@R: c(person("Nikolas", "Kuschnig", role = c("aut", "cre"), email = "nikolas.kuschnig@wu.ac.at", comment = c(ORCID = "0000-0002-6642-2543")), person("Lukas", "Vashold", role = "aut", comment = c(ORCID = "0000-0002-3562-3414")), person("Nirai", "Tomass", role = "ctb"), person("Michael", "McCracken", role = "dtc"), person("Serena", "Ng", role = "dtc"))
# Author: Nikolas Kuschnig [aut, cre] (<https://orcid.org/0000-0002-6642-2543>), Lukas Vashold [aut] (<https://orcid.org/0000-0002-3562-3414>), Nirai Tomass [ctb], Michael McCracken [dtc], Serena Ng [dtc]
# Maintainer: Nikolas Kuschnig <nikolas.kuschnig@wu.ac.at>
# Description: Estimation of hierarchical Bayesian vector autoregressive models following Kuschnig & Vashold (2021) <doi:10.18637/jss.v100.i14>. Implements hierarchical prior selection for conjugate priors in the fashion of Giannone, Lenza & Primiceri (2015) <doi:10.1162/REST_a_00483>. Functions to compute and identify impulse responses, calculate forecasts, forecast error variance decompositions and scenarios are available. Several methods to print, plot and summarise results facilitate analysis.
# URL: https://github.com/nk027/bvar
# BugReports: https://github.com/nk027/bvar/issues
# Depends: R (>= 3.3.0)
# Imports: mvtnorm, stats, graphics, utils, grDevices
# Suggests: coda, vars, tinytest
# License: GPL-3 | file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-03-08 18:37:16 UTC; nikolas
# Repository: CRAN
# Date/Publication: 2023-03-08 19:30:06 UTC
